image: node:alpine

variables:

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  before_script:
    - apk add --no-cache curl zip rsync
  script:
    - npm ci
    - npm run build:deployment
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    expire_in: 1 day
    paths:
      - dist
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $TARGET_HOST/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add --no-cache lftp openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - echo "Deploying for branch $CI_COMMIT_REF_SLUG – will be available at 🌎 $TARGET_HOST/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG"
  script:
    - lftp -e "set ftp:list-options -a; set net:timeout 5; set net:max-retries 3; set net:reconnect-interval-base 5; open sftp://$SFTP_HOST; user $SFTP_USER $SFTP_PASSWORD; mirror --reverse --delete ./dist/ $SFTP_FOLDER/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/; bye"
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $TARGET_HOST/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG
    on_stop: delete

delete:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update
    - apk add --no-cache lftp openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - lftp -e "set ftp:list-options -a; set net:timeout 5; set net:max-retries 3; set net:reconnect-interval-base 5; open sftp://$SFTP_HOST; user $SFTP_USER $SFTP_PASSWORD; rm -r $SFTP_FOLDER/$CI_PROJECT_NAME/$CI_COMMIT_REF_SLUG/; bye"
  when: manual
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
